server:
  port: 9090
  address: 172.16.201.211

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    messages:
      basename: messages
      encoding: UTF-8


  datasource:
    password: password
    url: jdbc:sqlserver://172.16.200.3;databaseName=TXCARD
    username: it

